### ISSUE TITLE
Yet another question about BFFNT

### ISSUE THREAD

**Issue by Joonie86** [wmltogether/Project-Console-Game-Localization#2]
Hi there, I'm wondering if this tool only supports Chinese?

我一直试过韩国语，不过好像这个工具不能处理韩文的 Message.bin Binary.

有空帮我看一下好吗？ 谢谢您。（我都会讲韩国话跟汉语）

**Comment by wmltogether** [comment]
Try this tool [FontConverter](https://drive.google.com/open?id=0B8aGRgqUf1t4V2NEQ1JOMEZUTXM)

It's an official tool leaked from WiiU Cafe SDK, It will help you create Korean *.BFFNT fonts.
:XD

**Comment by Joonie86** [comment]
Thanks for the info, however the game keeps crashing with the generated font.. 

I guess I could try re-importing cmap/cwdh/gtx manually from the generated font..

**Comment by wmltogether** [comment]
Since you can read Chinese, I can explain it more easily.(Sorry for my poor English again).
首先还是推荐使用 日语版 进行修改。英文版可能会在字库扩大后出现内存不足发生黑屏。
在我设计中文版脚本的时候，手中还没有WiiU SDK，所以采用了自己build cmap的方式，中文版制作很稳定。

后来有了WiiU SDK，这个工具还是比较稳定的，不会有什么错误，在其他几个游戏中已经测试过了。

关于字库的生成，推荐只在字库中放入英文字母，韩语字母和日语假名，整个TTF全部放入字库也会造成内存不足的。做法是 设计一个xlor文件(可以参考xlor目录中的例子)，在转换工具中选用filter ，来指定bffnt中需要的字符。

再最后还是要检查 rpx 的问题，一定要把修改过的file length 写在正确的offset位置，不然还是会黑屏的。
搜索正确的offset可以通过lfm_order中所有文件的length，搜索他们在elf中的offset，这是一个很明显的区域，搜索后很容易发现。

**Comment by Joonie86** [comment]
谢谢您， 我都解决了， 结果那个正式工具可以制作韩文字体。
请多多关照 ！
